name: Client Panel App Test Workflow

on:
  workflow_dispatch:

jobs:
  client-app-test:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Verify Node.js and npm version
        run: |
          node -v
          npm -v

      - name: Set locale and timezone
        run: |
          sudo timedatectl set-timezone Europe/Warsaw
          echo "LANG=pl_PL.UTF-8" | sudo tee -a /etc/environment
          echo "LC_ALL=pl_PL.UTF-8" | sudo tee -a /etc/environment
        env:
          LANG: pl_PL.UTF-8
          LC_ALL: pl_PL.UTF-8

      - name: Debug locale and timezone
        run: |
          echo "Current locale:"
          locale
          echo "Current timezone:"
          timedatectl

      - name: Cleanup order
        run: npm run order-cleanup

      - name: Run client panel app tests
        run: npm run client-panel-app-test

      - name: Upload Cypress artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
