name: All Test Workflow

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Install dependencies
        run: npm install

  set-locale:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Set locale to Polish
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
        env:
          LANG: pl_PL.UTF-8
          LC_ALL: pl_PL.UTF-8

  set-timezone:
    runs-on: ubuntu-latest
    needs: set-locale
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Warsaw

  debug-locale-timezone:
    runs-on: ubuntu-latest
    needs: set-timezone
    steps:
      - name: Debug locale and timezone
        run: |
          echo "Current locale:"
          locale
          echo "Current timezone:"
          timedatectl

  run-client-app-tests:
    runs-on: ubuntu-latest
    needs: debug-locale-timezone
    env:
      LANG: pl
      LC_ALL: pl_PL.UTF-8
      TZ: Europe/Warsaw
    steps:
      - name: Run client app tests
        run: npm run client-app-test

  run-healthcheck:
    runs-on: ubuntu-latest
    needs: run-client-app-tests
    steps:
      - name: Run healthcheck
        run: npm run panel-app-api-health-check

  run-panel-api-test:
    runs-on: ubuntu-latest
    needs: run-healthcheck
    steps:
      - name: Run panel API test
        run: npm run panel-app-api-test

  run-panel-client-test:
    runs-on: ubuntu-latest
    needs: run-panel-api-test
    steps:
      - name: Run panel client test
        run: npm run panel-app-client-test
