name: Panel App API Health Check Workflow

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 * * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Get Token and Log it
        run: |
          echo "Getting token..."
          TOKEN=$(npm run token-api-test) # Tutaj uruchamiasz swoje polecenie do uzyskania tokena, np. skrypt bash lub npm
          echo "Token: $TOKEN"  # Logowanie tokena w GitHub Actions
          echo "TOKEN=$token" >> $GITHUB_ENV  # Zapisanie tokena w zmiennej środowiskowej GitHub Actions


      - name: Run healthcheck
      # run: npm run panel-app-api-health-check