name: Panel App API Health Check Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.KEY }}
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get and Print Token
        run: |
          RESPONSE=$(curl -s -X POST "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${{ secrets.KEY }}" \
          -H "Content-Type: application/json" \
          --data-raw '{
            "clientType": "CLIENT_TYPE_WEB",
            "email": "'"${{ secrets.LOGIN }}"'",
            "password": "'"${{ secrets.PASSWORD }}"'",
            "returnSecureToken": true
          }')

          # Checking for response errors or success
          ERROR_MESSAGE=$(echo "$RESPONSE" | jq -r '.error.message // "No Error Message"')
          if [ "$ERROR_MESSAGE" != "No Error Message" ]; then
            echo "Error: $ERROR_MESSAGE"
            exit 1
          fi

          TOKEN=$(echo "$RESPONSE" | jq -r '.idToken')

          if [ "$TOKEN" != "null" ]; then
            echo "ID Token: $TOKEN"
          else
            echo "Failed to retrieve ID token"
            exit 1
          fi
        shell: bash
