name: All Test Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install Cypress
        run: npx cypress install

  client-app-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Restore Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Set locale and timezone
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
          sudo timedatectl set-timezone Europe/Warsaw
        env:
          LANG: pl_PL.UTF-8
          LC_ALL: pl_PL.UTF-8

      - name: Run client app tests
        run: npm run client-app-test

  healthcheck:
    needs: client-app-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Restore Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Run healthcheck
        run: npm run panel-app-api-health-check

  panel-api-test:
    needs: healthcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Restore Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Run panel API test
        run: npm run panel-app-api-test

  panel-client-test:
    needs: panel-api-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Restore Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Run panel client test
        run: npm run panel-app-client-test
