name: All Test Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.KEY }}
      X_GITHUB_ACTION: ${{ secrets.X_GITHUB_ACTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Set locale and timezone
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
          sudo timedatectl set-timezone Europe/Warsaw
        env:
          LANG: pl_PL.UTF-8
          LC_ALL: pl_PL.UTF-8

      - name: Debug locale and timezone
        run: |
          echo "Current locale:"
          locale
          echo "Current timezone:"
          timedatectl

      - name: Run client app tests
        continue-on-error: true
        run: npm run client-app-test

      - name: Run healthcheck
        continue-on-error: true
        run: npm run panel-app-api-health-check

      - name: Run panel API test
        continue-on-error: true
        run: npm run panel-app-api-test

      - name: Run panel client test
        continue-on-error: true
        run: npm run panel-app-client-test
